export const RECIEVE_SURVEYS = 'RECIEVE_SURVEYS'
export const RECIEVE_SURVEY = 'RECIEVE_SURVEY'
export const RECIEVE_PATHNAME = 'RECIEVE_PATHNAME'
export const SET_PARTICIPATION = 'SET_PARTICIPATION'
